# Generated by Django 4.0 on 2022-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_alter_patients_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='remarque',
            field=models.TextField(blank=True),
        ),
    ]
